### ISSUE TITLE
Request: CCXT support

### ISSUE THREAD

**Issue by deciphercypher** [iconomi-ag/iconomi-api#14]
This is a Request to enable CCXT support for Iconomi. This would surely attract many algorithmic traders to join the platform.

**Comment by matejsp** [comment]
Iconomi is not an exchange and we already do its own algorithmic trading for our users on various exchanges. CCXT is meant for exchanges. Iconomi does not have it's own orderbook or limit order or market order in the same sense as it is on exchange. The only applicable part would be balance. Maybe partially crypto strategies (market order).

Algorithmic traders would go directly to various exchanges and not via middleman Iconomi since they would get better performance being closer to the exchanges. Can you please specify your use case a bit more and what are you trying to achieve.

**Comment by deciphercypher** [comment]
Thank you for your reply! Yes, as you already suggested my use case would be to handle the asset allocation inside Iconomi with a (low frequency) algorithm that would pass market orders to Iconomi. I think CCXT support would be very helpful for this as it is  supported by a range of open source trading frameworks.
